### ISSUE TITLE
Error while running the rust+wasm in my docker

### ISSUE THREAD

**Issue by iamshreeram** [wasm-university/wasm-hosted-web-servers#1]
Hi @k33g , Following the [article](https://blog.kubesimplify.com/embed-http-servers-in-wasm-with-rust-and-csharp), building the docker image works well but it errors out while `docker run` 

```
docker run -dp 8080:8080 --name=wasmservice --runtime=io.containerd.wasmedge.v1 --platform=wasi/wasm32 wasmservice
```

We are seeing the below error message while running the container 
```
3fe7bea7f050ac3f0d5c29c2576dbaad2b7e977b7e3ad06ed570ef7f6ee1171d
docker: Error response from daemon: failed to create task for container: failed to start shim: start failed: /usr/local/bin/containerd-shim-wasmedge-v1: error while loading shared libraries: libwasmedge.so.0: cannot open shared object file: No such file or directory
: exit status 127: unknown.
```

Machine : Mac M1
Status of the docker image : `Created`

Thanks!

**Comment by k33g** [comment]
Oh, it's an old blog post, and I only used Wasm and Docker for a long time. There are some changes. 
You should try with `--platform=wasi/wasm` and be sure to setup Docker Desktop correctly: https://www.docker.com/blog/announcing-dockerwasm-technical-preview-2/

**Comment by iamshreeram** [comment]
@k33g , Yea, Looks like the setup process of `containerd-shim-wasmtime` runtime is little tricky with Mac OS; Finding some way out. thanks!
